-- Create customers table for multi-tenant architecture
-- customer_id serves as tenant_id throughout the application

-- Create sequence for 8-digit customer IDs
CREATE SEQUENCE IF NOT EXISTS customers_id_seq
    START WITH 10000000
    INCREMENT BY 1
    MINVALUE 10000000
    MAXVALUE 99999999
    NO CYCLE;

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER PRIMARY KEY DEFAULT nextval('customers_id_seq'),
    
    -- Required fields
    customer_name VARCHAR(255) NOT NULL,
    customer_category VARCHAR(50) NOT NULL CHECK (customer_category IN ('SCHOOL', 'SHOP', 'WAREHOUSE')),
    customer_type VARCHAR(50) NOT NULL CHECK (customer_type IN ('Contract', 'Permanent')),
    
    -- Contact information
    contact_person VARCHAR(255),
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    
    -- Address fields
    address_line1 TEXT,
    address_line2 TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'India',
    
    -- Business information
    tax_id VARCHAR(50) UNIQUE,
    registration_number VARCHAR(100),
    
    -- Status and metadata
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_category ON customers(customer_category);
CREATE INDEX IF NOT EXISTS idx_customers_is_active ON customers(is_active);
CREATE INDEX IF NOT EXISTS idx_customers_tax_id ON customers(tax_id) WHERE tax_id IS NOT NULL;

-- Create trigger function for updating updated_at timestamp
CREATE OR REPLACE FUNCTION update_customers_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at on row modification
DROP TRIGGER IF EXISTS update_customers_updated_at ON customers;
CREATE TRIGGER update_customers_updated_at
    BEFORE UPDATE ON customers
    FOR EACH ROW
    EXECUTE FUNCTION update_customers_updated_at_column();

-- Add comment to table
COMMENT ON TABLE customers IS 'Master tenant table for multi-tenant architecture. customer_id is used as tenant_id throughout the application.';
COMMENT ON COLUMN customers.customer_id IS '8-digit autogenerated tenant identifier (range: 10000000-99999999)';
COMMENT ON COLUMN customers.customer_category IS 'Business category: SCHOOL, SHOP, or WAREHOUSE';
COMMENT ON COLUMN customers.customer_type IS 'Engagement type: Contract or Permanent';
