-- Create tenants table for multi-tenant architecture
-- tenant_id serves as unique identifier throughout the application

-- Create sequence for 8-digit tenant IDs
CREATE SEQUENCE IF NOT EXISTS tenants_id_seq
    START WITH 10000000
    INCREMENT BY 1
    MINVALUE 10000000
    MAXVALUE 99999999
    NO CYCLE;

-- Create tenants table
CREATE TABLE IF NOT EXISTS tenants (
    tenant_id INTEGER PRIMARY KEY DEFAULT nextval('tenants_id_seq'),
    
    -- Required fields
    tenant_name VARCHAR(255) NOT NULL,
    tenant_category VARCHAR(50) NOT NULL CHECK (tenant_category IN ('SCHOOL', 'SHOP', 'WAREHOUSE')),
    tenant_type VARCHAR(50) NOT NULL CHECK (tenant_type IN ('Contract', 'Permanent')),
    
    -- Contact information
    contact_person VARCHAR(255),
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    
    -- Address fields
    address_line1 TEXT,
    address_line2 TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'India',
    
    -- Business information
    tax_id VARCHAR(50) UNIQUE,
    registration_number VARCHAR(100),
    
    -- Status and metadata
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_tenants_email ON tenants(email);
CREATE INDEX IF NOT EXISTS idx_tenants_category ON tenants(tenant_category);
CREATE INDEX IF NOT EXISTS idx_tenants_is_active ON tenants(is_active);
CREATE INDEX IF NOT EXISTS idx_tenants_tax_id ON tenants(tax_id) WHERE tax_id IS NOT NULL;

-- Create trigger function for updating updated_at timestamp
CREATE OR REPLACE FUNCTION update_tenants_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at on row modification
DROP TRIGGER IF EXISTS update_tenants_updated_at ON tenants;
CREATE TRIGGER update_tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW
    EXECUTE FUNCTION update_tenants_updated_at_column();

-- Add comment to table
COMMENT ON TABLE tenants IS 'Master tenant table for multi-tenant architecture.';
COMMENT ON COLUMN tenants.tenant_id IS '8-digit autogenerated tenant identifier (range: 10000000-99999999)';
COMMENT ON COLUMN tenants.tenant_category IS 'Business category: SCHOOL, SHOP, or WAREHOUSE';
COMMENT ON COLUMN tenants.tenant_type IS 'Engagement type: Contract or Permanent';

