# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/upendra_verma/StarLightERP/StarLightERP_Backend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/upendra_verma/StarLightERP/StarLightERP_Backend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/upendra_verma/StarLightERP/StarLightERP_Backend/CMakeFiles /home/upendra_verma/StarLightERP/StarLightERP_Backend//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/upendra_verma/StarLightERP/StarLightERP_Backend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StarLightERP_Backend_Temp

# Build rule for target.
StarLightERP_Backend_Temp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StarLightERP_Backend_Temp
.PHONY : StarLightERP_Backend_Temp

# fast build rule for target.
StarLightERP_Backend_Temp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/build
.PHONY : StarLightERP_Backend_Temp/fast

#=============================================================================
# Target rules for targets named StarLightERP_Backend_Temp_test

# Build rule for target.
StarLightERP_Backend_Temp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StarLightERP_Backend_Temp_test
.PHONY : StarLightERP_Backend_Temp_test

# fast build rule for target.
StarLightERP_Backend_Temp_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/StarLightERP_Backend_Temp_test.dir/build.make test/CMakeFiles/StarLightERP_Backend_Temp_test.dir/build
.PHONY : StarLightERP_Backend_Temp_test/fast

controllers/AppsController.o: controllers/AppsController.cc.o
.PHONY : controllers/AppsController.o

# target to build an object file
controllers/AppsController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AppsController.cc.o
.PHONY : controllers/AppsController.cc.o

controllers/AppsController.i: controllers/AppsController.cc.i
.PHONY : controllers/AppsController.i

# target to preprocess a source file
controllers/AppsController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AppsController.cc.i
.PHONY : controllers/AppsController.cc.i

controllers/AppsController.s: controllers/AppsController.cc.s
.PHONY : controllers/AppsController.s

# target to generate assembly for a file
controllers/AppsController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AppsController.cc.s
.PHONY : controllers/AppsController.cc.s

controllers/AuthController.o: controllers/AuthController.cc.o
.PHONY : controllers/AuthController.o

# target to build an object file
controllers/AuthController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AuthController.cc.o
.PHONY : controllers/AuthController.cc.o

controllers/AuthController.i: controllers/AuthController.cc.i
.PHONY : controllers/AuthController.i

# target to preprocess a source file
controllers/AuthController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AuthController.cc.i
.PHONY : controllers/AuthController.cc.i

controllers/AuthController.s: controllers/AuthController.cc.s
.PHONY : controllers/AuthController.s

# target to generate assembly for a file
controllers/AuthController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/AuthController.cc.s
.PHONY : controllers/AuthController.cc.s

controllers/CustomerController.o: controllers/CustomerController.cc.o
.PHONY : controllers/CustomerController.o

# target to build an object file
controllers/CustomerController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/CustomerController.cc.o
.PHONY : controllers/CustomerController.cc.o

controllers/CustomerController.i: controllers/CustomerController.cc.i
.PHONY : controllers/CustomerController.i

# target to preprocess a source file
controllers/CustomerController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/CustomerController.cc.i
.PHONY : controllers/CustomerController.cc.i

controllers/CustomerController.s: controllers/CustomerController.cc.s
.PHONY : controllers/CustomerController.s

# target to generate assembly for a file
controllers/CustomerController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/CustomerController.cc.s
.PHONY : controllers/CustomerController.cc.s

controllers/HealthController.o: controllers/HealthController.cc.o
.PHONY : controllers/HealthController.o

# target to build an object file
controllers/HealthController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/HealthController.cc.o
.PHONY : controllers/HealthController.cc.o

controllers/HealthController.i: controllers/HealthController.cc.i
.PHONY : controllers/HealthController.i

# target to preprocess a source file
controllers/HealthController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/HealthController.cc.i
.PHONY : controllers/HealthController.cc.i

controllers/HealthController.s: controllers/HealthController.cc.s
.PHONY : controllers/HealthController.s

# target to generate assembly for a file
controllers/HealthController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/HealthController.cc.s
.PHONY : controllers/HealthController.cc.s

controllers/JWTUtils.o: controllers/JWTUtils.cc.o
.PHONY : controllers/JWTUtils.o

# target to build an object file
controllers/JWTUtils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/JWTUtils.cc.o
.PHONY : controllers/JWTUtils.cc.o

controllers/JWTUtils.i: controllers/JWTUtils.cc.i
.PHONY : controllers/JWTUtils.i

# target to preprocess a source file
controllers/JWTUtils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/JWTUtils.cc.i
.PHONY : controllers/JWTUtils.cc.i

controllers/JWTUtils.s: controllers/JWTUtils.cc.s
.PHONY : controllers/JWTUtils.s

# target to generate assembly for a file
controllers/JWTUtils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/JWTUtils.cc.s
.PHONY : controllers/JWTUtils.cc.s

controllers/SecurityUtils.o: controllers/SecurityUtils.cc.o
.PHONY : controllers/SecurityUtils.o

# target to build an object file
controllers/SecurityUtils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/SecurityUtils.cc.o
.PHONY : controllers/SecurityUtils.cc.o

controllers/SecurityUtils.i: controllers/SecurityUtils.cc.i
.PHONY : controllers/SecurityUtils.i

# target to preprocess a source file
controllers/SecurityUtils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/SecurityUtils.cc.i
.PHONY : controllers/SecurityUtils.cc.i

controllers/SecurityUtils.s: controllers/SecurityUtils.cc.s
.PHONY : controllers/SecurityUtils.s

# target to generate assembly for a file
controllers/SecurityUtils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/SecurityUtils.cc.s
.PHONY : controllers/SecurityUtils.cc.s

controllers/TenantTestController.o: controllers/TenantTestController.cc.o
.PHONY : controllers/TenantTestController.o

# target to build an object file
controllers/TenantTestController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/TenantTestController.cc.o
.PHONY : controllers/TenantTestController.cc.o

controllers/TenantTestController.i: controllers/TenantTestController.cc.i
.PHONY : controllers/TenantTestController.i

# target to preprocess a source file
controllers/TenantTestController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/TenantTestController.cc.i
.PHONY : controllers/TenantTestController.cc.i

controllers/TenantTestController.s: controllers/TenantTestController.cc.s
.PHONY : controllers/TenantTestController.s

# target to generate assembly for a file
controllers/TenantTestController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/TenantTestController.cc.s
.PHONY : controllers/TenantTestController.cc.s

controllers/UserController.o: controllers/UserController.cc.o
.PHONY : controllers/UserController.o

# target to build an object file
controllers/UserController.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/UserController.cc.o
.PHONY : controllers/UserController.cc.o

controllers/UserController.i: controllers/UserController.cc.i
.PHONY : controllers/UserController.i

# target to preprocess a source file
controllers/UserController.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/UserController.cc.i
.PHONY : controllers/UserController.cc.i

controllers/UserController.s: controllers/UserController.cc.s
.PHONY : controllers/UserController.s

# target to generate assembly for a file
controllers/UserController.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/controllers/UserController.cc.s
.PHONY : controllers/UserController.cc.s

filters/TenantMiddleware.o: filters/TenantMiddleware.cc.o
.PHONY : filters/TenantMiddleware.o

# target to build an object file
filters/TenantMiddleware.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/filters/TenantMiddleware.cc.o
.PHONY : filters/TenantMiddleware.cc.o

filters/TenantMiddleware.i: filters/TenantMiddleware.cc.i
.PHONY : filters/TenantMiddleware.i

# target to preprocess a source file
filters/TenantMiddleware.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/filters/TenantMiddleware.cc.i
.PHONY : filters/TenantMiddleware.cc.i

filters/TenantMiddleware.s: filters/TenantMiddleware.cc.s
.PHONY : filters/TenantMiddleware.s

# target to generate assembly for a file
filters/TenantMiddleware.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/filters/TenantMiddleware.cc.s
.PHONY : filters/TenantMiddleware.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StarLightERP_Backend_Temp.dir/build.make CMakeFiles/StarLightERP_Backend_Temp.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... StarLightERP_Backend_Temp"
	@echo "... StarLightERP_Backend_Temp_test"
	@echo "... controllers/AppsController.o"
	@echo "... controllers/AppsController.i"
	@echo "... controllers/AppsController.s"
	@echo "... controllers/AuthController.o"
	@echo "... controllers/AuthController.i"
	@echo "... controllers/AuthController.s"
	@echo "... controllers/CustomerController.o"
	@echo "... controllers/CustomerController.i"
	@echo "... controllers/CustomerController.s"
	@echo "... controllers/HealthController.o"
	@echo "... controllers/HealthController.i"
	@echo "... controllers/HealthController.s"
	@echo "... controllers/JWTUtils.o"
	@echo "... controllers/JWTUtils.i"
	@echo "... controllers/JWTUtils.s"
	@echo "... controllers/SecurityUtils.o"
	@echo "... controllers/SecurityUtils.i"
	@echo "... controllers/SecurityUtils.s"
	@echo "... controllers/TenantTestController.o"
	@echo "... controllers/TenantTestController.i"
	@echo "... controllers/TenantTestController.s"
	@echo "... controllers/UserController.o"
	@echo "... controllers/UserController.i"
	@echo "... controllers/UserController.s"
	@echo "... filters/TenantMiddleware.o"
	@echo "... filters/TenantMiddleware.i"
	@echo "... filters/TenantMiddleware.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

